/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.graphs;

import java.util.ArrayList;

/**
 *
 * @author RJ
 */
public class GraphsFrame extends javax.swing.JFrame {

    private EnergyTrendPane powerTrendPane;

    /**
     * Creates new form PowerTrendGraphFrame
     */
    public GraphsFrame() {
        initComponents();
        customInit();
    }

    public GraphsFrame(ArrayList<Integer> memberNodeCountList,ArrayList<Integer> externalNodeCountList, ArrayList<Double> powerValuesList) {
        initComponents();
        customInit(memberNodeCountList,externalNodeCountList, powerValuesList);
    }

    private void customInit() {
        powerTrendPane = new EnergyTrendPane();
        powerTrendPane.setName("Ext. Nodes Vs Energy");
        tabbedPane.add(powerTrendPane);

        setTitle("Test");
    }

    private void customInit(ArrayList<Integer> memberNodeCountList,ArrayList<Integer> externalNodeCountList, ArrayList<Double> powerValuesList) {
        powerTrendPane = new EnergyTrendPane(memberNodeCountList,externalNodeCountList, powerValuesList);
        powerTrendPane.setName("Ext. Nodes Vs Energy");
        tabbedPane.add(powerTrendPane);
        
        setTitle("Graphical Analysis");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1016, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
