/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.controls;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author SHRI
 */
public class ChooseAnalysisDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChooseAnalysisDialog
     */
    public ChooseAnalysisDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseAnalysisPanel = new javax.swing.JPanel();
        selectDetectedNodeLabel = new javax.swing.JLabel();
        selectDetectedNodeComboBox = new javax.swing.JComboBox();
        showAlgorithmAnalysisButton = new javax.swing.JButton();
        showGraphicalAnalysisButton = new javax.swing.JButton();
        resetGraphicalAnalysisButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Analysis ");
        setAutoRequestFocus(false);
        setFocusableWindowState(false);
        getContentPane().setLayout(null);

        chooseAnalysisPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 255)));
        chooseAnalysisPanel.setLayout(null);

        selectDetectedNodeLabel.setText("Select Detected Nodes:");
        chooseAnalysisPanel.add(selectDetectedNodeLabel);
        selectDetectedNodeLabel.setBounds(20, 60, 150, 20);

        selectDetectedNodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseAnalysisPanel.add(selectDetectedNodeComboBox);
        selectDetectedNodeComboBox.setBounds(160, 60, 90, 20);

        showAlgorithmAnalysisButton.setText("Analysis");
        showAlgorithmAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAlgorithmAnalysisButtonActionPerformed(evt);
            }
        });
        chooseAnalysisPanel.add(showAlgorithmAnalysisButton);
        showAlgorithmAnalysisButton.setBounds(260, 58, 130, 23);

        showGraphicalAnalysisButton.setText("Graphical Analysis");
        chooseAnalysisPanel.add(showGraphicalAnalysisButton);
        showGraphicalAnalysisButton.setBounds(20, 120, 160, 23);

        resetGraphicalAnalysisButton.setText("Reset Graphs");
        chooseAnalysisPanel.add(resetGraphicalAnalysisButton);
        resetGraphicalAnalysisButton.setBounds(190, 120, 200, 23);

        getContentPane().add(chooseAnalysisPanel);
        chooseAnalysisPanel.setBounds(0, 0, 410, 200);

        setBounds(800, 200, 425, 237);
    }// </editor-fold>//GEN-END:initComponents

    private void showAlgorithmAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAlgorithmAnalysisButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAlgorithmAnalysisButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseAnalysisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseAnalysisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseAnalysisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseAnalysisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooseAnalysisDialog dialog = new ChooseAnalysisDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getResetGraphicalAnalysisButton() {
        return resetGraphicalAnalysisButton;
    }

    public JComboBox getSelectDetectedNodeComboBox() {
        return selectDetectedNodeComboBox;
    }

    public JButton getShowAlgorithmAnalysisButton() {
        return showAlgorithmAnalysisButton;
    }

    public JButton getShowGraphicalAnalysisButton() {
        return showGraphicalAnalysisButton;
    }

    public JLabel getSelectDetectedNodeLabel() {
        return selectDetectedNodeLabel;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chooseAnalysisPanel;
    private javax.swing.JButton resetGraphicalAnalysisButton;
    private javax.swing.JComboBox selectDetectedNodeComboBox;
    private javax.swing.JLabel selectDetectedNodeLabel;
    private javax.swing.JButton showAlgorithmAnalysisButton;
    private javax.swing.JButton showGraphicalAnalysisButton;
    // End of variables declaration//GEN-END:variables
}
